---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4772589121-zKbxF15ifutBrur6Blkr6redhJcB9hZ8GqKK9rI
:access_token_secret: HQuzs4nQe6lDQLn0Uz4oqsQorPmefl4l52Cl4APDSNZQr
